name: unit-tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]

# ensure testing on actual specified versions, and not auto-upgraded toolchain
# versions
env:
  GOTOOLCHAIN: local

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Src Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26.x'
        check-latest: true
      id: go

    - name: Tests
      env:
        GO111MODULE: "on"
        GOPROXY: "https://proxy.golang.org"
      run: go test -v -cpu=1,2 ./...
